site_name: Wandering Stag
site_author: Skyler Hart
site_description: Test description

repo_name: WanderingStag/WSTools
repo_url: https://github.com/WanderingStag/WSTools

nav:
  - Home: 'index.md'
  - WSTools:
    - "Issues": https://github.com/WanderingStag/WSTools/issues
    - "Report Security Issue": https://github.com/WanderingStag/WSTools/security

theme:
  name: material
  logo: wanderingstag_logo.svg
  favicon: wanderingstag_logo.svg
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search

copyright: >
  Copyright &copy; 2011 - 2023 Wandering Stag, LLC and Skyler Hart
